### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iftybito67**
# PR: Thank you!

## Reason

- [x] Fix: Wrong information
- [ ] Fix: Typo error
- [ ] Fix: License violation
- [ ] Add: New Item

## Type

- [x] Cloud
- [ ] S3
- [ ] Self-hosted

## Name

Box downgraded their free tier to give 10 gb now

## Link

[_box.com_](https://www.box.com/pricing/individual)

## Thank you for improving project

**This helps others find hosting of their choise**

### CODE REVIEW

**Comment by dalisoft** [comment]
@iftybito67 thank you for pr. 
isn't they are offering 30gb for download mobile app?
For me it was such case

**Comment by iftybito67** [comment]
maybe its region dependent? I just downloaded the app to check but it says, box individual 10 GB free

**Comment by dalisoft** [comment]
@iftybito67 then this PR is actual and thank you again

**Comment by iftybito67** [comment]
@dalisoft thank you for merging
i am new and this is my first merged pull req so thanks

**Comment by dalisoft** [comment]
@iftybito67 You found change. I am provide these list for users and if new users does not get 30GB then it's 10GB

**Pull request merged**
